interface WaybillManagementIndexModel{
    id: string,
    department: string,
    singleNumber: string,
    awb: string,
    salesman: string,
    deliveryTel: string,
    city: string,
    receiptTel: string,
    origin:string,
    destination: string,
    driver: string,
    payment: string,
    deliveryType: string,
    paymentType: string,
    collection: string,
    ynpayment: string,
    receiptStates: string,
    auditStates: string,
    createData: string,

    states: string,
    orderNumber: string,
    orderData: string,
    goodsWeight: string,
    volume: string,
    goodsNumber: string,
    delivery: string,
    goodspeople: string,
    LicensePlateNumber: String,
    models: string,
    transitLine: string,
    receipt: string,
    powerOfAttorney: string,
    reconciliationStates: string,
    collectionMoney: string,
    freight: string,
    StoragCharges: string,
    warehouseEntry: string,
    OtherReceivables: string,
    paymentMoney: string,
    tax: string,
    driverMoney: string,
    PickMoney: string,
    transitMoney: string,
    fuelMoney: string,
    OtherToCopeWith: String,
    

}